### ISSUE TITLE
App requires restart after waking from sleep

### ISSUE THREAD

**Issue by jr-pe** [rxhanson/Middle-Community#38] opened 2022-03-08 13:54 UTC
When my M1 Mac wakes from sleep, I often need to quit and restart the app. This happens frequently but inconsistently.
 
Please let me know if you need any logs or additional info.

**Comment by jomast** [comment] 2022-03-11 15:21
I too have found the same behavior. I have to start the app again. (I assume it's crashing)

**Comment by rxhanson** [comment] 2022-03-11 15:57
Up for testing out a beta?

https://middleclick.app/downloads/Middle1.6.10.dmg

**Comment by rxhanson** [comment] 2022-03-11 15:58
As a side note, the issue is that the app restarts itself on wake, and it appears that there are certain conditions that prevent the app from performing the launch after the close on certain macs.

**Comment by jomast** [comment] 2022-03-11 17:55
> Up for testing out a beta?
> 
> https://middleclick.app/downloads/Middle1.6.10.dmg

Just tried twice and both times Middle (v1.6.10) failed to restart on wake.

**Comment by rxhanson** [comment] 2022-03-11 18:03
Thanks! This beta used an sh command to kill then restart the app. Do you have Middle installed in a location other than /Applications? 

If you don't mind, can you execute `open <path to Middle.app>` in the terminal and see if it fails? That's what seems to be failing here. So, if it is in /Applications it would be `open /Applications/Middle.app`.

**Comment by jomast** [comment] 2022-03-11 18:33
```shell
jomast@ria3 $ ls -l /Applications | grep Middle
drwxr-xr-x@ 3 jomast  admin    96B Mar 11 10:26 Middle.app/
```

It opens as expected when I run `open /Applications/Middle.app`

**Comment by rxhanson** [comment] 2022-03-13 03:29
Thanks again. I would greatly appreciate if you can try out another beta where I think I have this fixed:

https://middleclick.app/downloads/Middle1.6.11.dmg

**Comment by jomast** [comment] 2022-03-13 16:45
Same behavior with `v1.6.11` I'm sorry to say.

**Comment by souricevincent** [comment] 2022-03-14 23:14
I have about the same problem. I use my closed mac on an external screen and when I finish the day, I unplug my mac and open it. I have to restart the application to get it to work again.

Software:

    System Software Overview:

      System Version: macOS 12.2.1 (21D62)
      Kernel Version: Darwin 21.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro13,2
      Processor Name: Dual-Core Intel Core i7
      Processor Speed: 3,3 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 447.80.3.0.0
      OS Loader Version: 540.80.2~11

**Comment by rxhanson** [comment] 2022-03-15 01:44
Alright, can anyone run this beta and send me the logs? 
https://middleclick.app/downloads/Middle1.6.12.dmg

The logs get cleared on launch so, in order to get proper logs, don't restart the app when it fails to launch.

I will need both middle.log and middleHelper.log from this location:
~/Library/Application Support/Middle

**Comment by rxhanson** [comment] 2022-03-15 22:31
This is it (I hope):

https://middleclick.app/downloads/Middle1.6.13.dmg

**Comment by jomast** [comment] 2022-03-16 01:52
Sorry, same behavior.

middle.log
```
14:24:12.169 INFO AppDelegate.applicationDidFinishLaunching():71 - build 75
```

**Comment by rxhanson** [comment] 2022-03-16 15:23
Thanks for the quick response. This one is a little different.
https://middleclick.app/downloads/Middle1.6.14.dmg

First, delete the existing version that you have, that will guarantee the helper is not running if for some reason it still is. 

Next, when you run v1.6.14, you can force the restart using the menu bar menu. If you don't mind, try each of the three relaunch types in there and see if any of them work for you.

Here's what's been going on:
As you can tell, there are effectively two ways that you can relaunch an app: using a helper application or using commands. Before all of these attempts you've tried, Middle would try to use the command, and if that didn't launch the app then it would use the helper app. Turns out that the helper application could get stuck as a background process and become unresponsive (maybe due to M1?). My latest updates should fix that. We've seen that the "command" method doesn't launch the app for some reason. Initially I thought it was due to timing, and that the app wouldn't relaunch itself because it thought it was already running. That doesn't seem to be the case, but rather I think it is not properly resolving the path. The weird thing there is that it doesn't have issues with that all the time, on every mac. In this version I scrapped it since that wasn't working and now just issue "open -a Middle". This leaves room for ambiguity, but better than the alternative of it just not working at all. 

My desired default behavior is to not use a command, but rather to use only the helper app. By doing so, I can have more control over what happens, and in the latest version, if the helper app is unresponsive then it will err on the side of not terminating the app on wake. The problem with not restarting the app on wake is that macOS can fail to resume sending touch data to the app on wake and this is only fixed by a restart. So, worst case here is that the app is unresponsive, but at least it didn't appear that it crashed.

Bizarrely complicated for a seemingly trivial task.

@jomast I appreciate all your help testing this out. If you want license keys to any of my other apps just send me an email.

**Comment by adambkovacs** [comment] 2022-03-16 17:54
I had the same problem, using M1 air, using version 1.6.14 now, will let you know if the issue is still there!

**Comment by jomast** [comment] 2022-03-16 19:48
I don't want to speak too soon, but so far, after a few quick tests, `v1.6.14` is working great with the desired behavior. 🎉

**Comment by adambkovacs** [comment] 2022-03-16 23:49
Unfortonutaly nothing changed on my end. I had to manually restart after wake. Not sure if it's normal behavior, but the Middle app was running just not working, I had quit and restart it.
No Middle folder under `Library/Application Support/`so can't send any logs.

**Comment by rxhanson** [comment] 2022-03-17 00:07
@adambkovacs 
1. Did you delete your old version before installing the new one?
2. When your mac wakes from sleep and Middle is unresponsive, can you try to relaunch the app using the options in the menu bar menu? First try the 'helper', and if it doesn't do anything then try 'process' and let me know what you find.

**Comment by aeons** [comment] 2022-03-17 07:41
For reference 1.6.13 seems to work for me, on a M1.

**Comment by rxhanson** [comment] 2022-03-17 20:10
Thanks all. I'm sticking with the approach in v1.6.14, and it's getting rolled into an official release, v1.7 (meaning they are identical in this regard). I'm pretty confident that the issue is fixed here, as long as you guarantee that the old launcher application from before 1.6.13 is not running. This can be done by deleting the app and reinstalling from scratch (regardless of version), finding the MiddleLauncher in Activity Monitor and killing it, or restarting or logging out/in your mac. 

If anyone has gone through those steps with v1.7 and it's still having the issue, then I'll detail how to produce logs this time around.

**Comment by jpaulickcz** [comment] 2022-03-18 08:21
Hi, I just got the update prompt which lead me here.

I've been having the same issue on my 2017 Intel w/ Monterey, but never bother to investigate.

I was just wondering whether the usual update from the prompt is enough for proper update, or if I should do any extra steps to make sure I only have 100% the v1.7?

**Comment by rxhanson** [comment] 2022-03-18 11:46
@jpaulickcz just updating might work, but it’s probably worth it to make sure the MiddleLauncher is not running in Activity Monitor before or after updating.

**Comment by jomast** [comment] 2022-03-22 00:28
I'm now, randomly, getting this after it wakes from sleep: 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/24574126/159383710-9114838a-5386-4743-a89d-1f49e2714378.png">
Sometimes it continues to work as expected... sometimes its running, but not responsive... sometimes it's simply not running.

* Middle `v1.7`
* Macbook Air M1
* MacOS 12.2.1

**Comment by rxhanson** [comment] 2022-03-22 02:01
Hmm. I’m pretty sure I can fix the message being displayed, and I have a thought about some next steps to try. I’ll post back when an update is ready.

**Comment by adambkovacs** [comment] 2022-03-22 02:55
> I'm now, randomly, getting this after it wakes from sleep: <img alt="image" width="252" src="https://user-images.githubusercontent.com/24574126/159383710-9114838a-5386-4743-a89d-1f49e2714378.png"> Sometimes it continues to work as expected... sometimes its running, but not responsive... sometimes it's simply not running.
> 
> * Middle `v1.7`
> * Macbook Air M1
> * MacOS 12.2.1

I have exactly the same issues

**Comment by rxhanson** [comment] 2022-03-23 02:16
@jomast, @adambkovacs, Please try v1.7.1. This version does have logging that will appear in `~/Library/Application Support/Middle`

https://middleclick.app/downloads/Middle1.7.1.dmg

@jpaulickcz, unfortunately that is an issue that would lean more toward a fix within macOS, even if it is something triggered by Middle. It sounds like a degradation of the gesture event stream coming from macOS. It seems that issues like this are more likely to appear if other apps that listen to the event stream like this are running, but that's not always the case.

**Comment by jpaulickcz** [comment] 2022-03-23 07:59
@rxhanson ok, that makes sense. Apart from this one-time issue the Middle after 1.7 worked well otherwise after waking up from sleep.

**Comment by adambkovacs** [comment] 2022-03-24 02:35
> @jomast, @adambkovacs, Please try v1.7.1. This version does have logging that will appear in `~/Library/Appl_icati_on Support/Middle`
> 
> https://middleclick.app/downloads/Middle1.7.1.dmg
> 
> @jpaulickcz, unfortunately that is an issue that would lean more toward a fix within macOS, even if it is something triggered by Middle. It sounds like a degradation of the gesture event stream coming from macOS. It seems that issues like this are more likely to appear if other apps that listen to the event stream like this are running, but that's not always the case.

thank you, trying now!

**Comment by rxhanson** [comment] 2022-03-24 15:52
@adambkovacs, @jomast, I was able to reproduce the MiddleLauncher warning finally, on v1.7.1, and will have another beta out shortly.

**Comment by rxhanson** [comment] 2022-03-24 17:37
I still have some more testing to do, but here's the latest beta if anyone wants to give it a go:

https://middleclick.app/downloads/Middle1.7.2.dmg

**Comment by rxhanson** [comment] 2022-03-24 21:33
@adambkovacs, @jomast v1.7.2 looks good to go from my testing. Hopefully this is finally it.

**Comment by jomast** [comment] 2022-03-25 00:42
I just did 4 tests and they all passed; though just before that it wasn't running... so I'm a cautious. I'll try again in the morning after a proper long sleep.

**Comment by jomast** [comment] 2022-03-25 13:46
Tried first thing in the morning and as I feared, Middle (v.1.7.2) is not running. Below are the logs if they help.

```
$ cat ~/Library/Application\ Support/Middle/middle.log
21:08:18.920 INFO AppDelegate.initializeLogging():74 - build 79
21:08:18.961 INFO AppDelegate.killLauncher():260 - Sending terminate message to launcher
23:08:34.526 INFO AppDelegate.killLauncher():260 - Sending terminate message to launcher
23:08:34.542 INFO AppDelegate.helperRelaunch():414 - Launching Middle helper
23:08:34.671 INFO AppDelegate.helperRelaunch():421 - Succesfully launched helper.
```

If you need any other logs, etc, let me know.

**Comment by rxhanson** [comment] 2022-03-25 14:06
If you can grab the launcher log as well, it's in a different place, unfortunately: ~/Library/Containers/com.knollsoft.MiddleLauncher/Data/Library/Application Support/Middle/middleHelper.log

**Comment by rxhanson** [comment] 2022-03-25 15:10
Even without seeing the launcher logs, I actually think I have a pretty clear picture of what's going on. It's likely that the launcher is just not waiting long enough for Middle to self terminate and for macOS to say that it's no longer running. The launcher will not relaunch Middle if macOS says it's still running, and things can move more slowly when waking from deep sleep. 

This next version will retry a couple times with a backoff time delay. I think this is what was needed, but if for some reason there are still issues, I'm pretty sure we are reaching the end of this endeavor.

https://middleclick.app/downloads/Middle1.7.3.dmg

**Comment by adambkovacs** [comment] 2022-03-25 22:19
testing :)

**Comment by rxhanson** [comment] 2022-03-26 02:46
I went ahead and released an official version (1.7.4) based on 1.7.3, mainly to get a release out that didn't show the "not open anymore" warning, but also to push an unrelated feature. It's OK to keep testing 1.7.3 if you started with that, since that part of the code has not changed.

**Comment by jomast** [comment] 2022-03-26 15:50
`v1.7.3` passed the "overnight sleep test"! I'll keep an eye on it, but I think this bug is finally dead. Nice work!

**Comment by rxhanson** [comment] 2022-03-26 17:11
@jomast Yay! Thanks for all your help. User of the year. Definitely send an email my way if you're looking for keys to any of my other apps.

**Comment by vip9** [comment] 2022-03-28 20:06
How to reset all wake-up settings to default? 
I was having issues with restarting, and set autoRestartOnWake to 2. Middle stayed running even after suspends.
When upgraded to 1.7.4. I've set it to 1. Now, after suspend, Middle is not running.

**Comment by rxhanson** [comment] 2022-03-28 20:19
@vip9 set it to 0

**Comment by rxhanson** [comment] 2022-04-01 04:15
Closing this one out. If anyone experiences issues with this now, please open a new issue and if necessary I will link it to this one.

**Closed by rxhanson** 2022-04-01 04:15 UTC

**Comment by adambkovacs** [comment] 2022-04-02 19:25
I've been on 1.7.4. and it's working perfectly, thanks for the fix @rxhanson !

**Comment by souricevincent** [comment] 2022-04-25 08:07
Hello, the deamon continues to crash regularly on my side. v:1.7.4
When I suspend the session. Or when I unplug the odinator from my screen. Or when it wakes up from sleep...

**Comment by phoerious** [comment] 2022-04-25 10:58
Can confirm that this is still an issue. Mostly after waking up from sleep, but also sometimes just randomly during normal operation.

**Comment by jpaulickcz** [comment] 2022-04-25 12:04
Same here (still). Just starting the app gets it going again so not much trouble, so I didn't report back here.

1.7.4 (80)
Monterey 12.2.1 + Intel

**Comment by rxhanson** [comment] 2022-04-25 14:30
Here's another update that fixes one more issue that I've found with the restart on wake:
https://middleclick.app/downloads/Middle1.7.5.dmg

If you try it and it still doesn't work, please provide logs, located at these two directories:
~/Library/Containers/com.knollsoft.MiddleLauncher/Data/Library/Application Support/Middle/middleHelper.log
~/Library/Application Support/Middle/middle.log

@souricevincent
Unplugging the laptop from your screen doesn't trigger Middle to restart itself (although it can be configured to do so via terminal command). This would point to something else going on. Is there a crash report for Middle in Console.app?

@phoerious 
Does the app quit randomly during normal operation, or does it just stop working? If it quits, then that would point to a crash and there should be a crash report in Console.app.

**Comment by phoerious** [comment] 2022-04-25 18:35
No, it just stops working, but continues to run in the background. When I launch another instance, it brings up the settings window, which I have to Cmd+Q and then restart it again.

**Comment by vip9** [comment] 2022-04-25 18:37
Got same behaviour from time to time (on two machines). It runs, but it does not "middles".

**Comment by rxhanson** [comment] 2022-04-25 21:05
@phoerious, @vip9 I've created a separate issue for tracking the issue where it stops working but continues to run:
https://github.com/rxhanson/Middle-Community/issues/45
